version: '3.8'
services:
  db:
    image: postgres:16.3
    container_name: vision_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vision
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data:
