// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        pgtype.UUID
	PostID    pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
}

type Post struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	AuthorID     pgtype.UUID
	Title        string
	Content      string
	RepoLink     pgtype.Text
	DemoLink     pgtype.Text
	PostImage    pgtype.Text
	LikeCount    pgtype.Int4
	CommentCount pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Reaction struct {
	ID           pgtype.UUID
	PostID       pgtype.UUID
	UserID       pgtype.UUID
	ReactionType string
	CreatedAt    pgtype.Timestamptz
}
