// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package data

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	ParentID  uuid.NullUUID
	UserID    uuid.UUID
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Post struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	AuthorID     uuid.UUID
	Title        string
	Content      string
	RepoLink     sql.NullString
	DemoLink     sql.NullString
	PostImage    sql.NullString
	LikeCount    int32
	CommentCount int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Reaction struct {
	ID           uuid.UUID
	PostID       uuid.UUID
	CommentID    uuid.NullUUID
	UserID       uuid.UUID
	ReactionType string
	CreatedAt    time.Time
}
